### ISSUE TITLE
PSBT key path serialization code doesn't match BIP

### ISSUE THREAD

**Issue by devrandom** [achow101/HWI#5]
The code here:  https://github.com/achow101/HWI/blob/master/serializations.py#L663 is calling the dictionary keys "fingerprint", but they are actually individual pubkeys.  Also, it doesn't actually put the fingerprint as the first value in the values array.

This is more of a documentation issue - the structure of the data is still correct, because fingerprints are 4 bytes.  It's just confusing to the reader and assumes the caller knows to have the first array element set to the fingerprint.

**Comment by achow101** [comment]
Resolved in 8837eca
