### ISSUE TITLE
p2sh-p2wpkh && bech32 support for getkeypool

### ISSUE THREAD

**Issue by instagibbs** [achow101/HWI#9]
I needs it.

**Comment by achow101** [comment]
I don't think this really matters since importing a pubkey imports all of the single key scripts for it, not just the one specified. This includes p2sh segwit and bech32 ones.

**Comment by instagibbs** [comment]
This is extremely <current version> Core behavior, but perhaps this lowers the immediate need for it.

**Comment by Sjors** [comment]
That had me confused for a while as well. In case someone does want to add it, this line would need to be changed: https://github.com/achow101/HWI/blob/master/hwilib/commands.py#L101

Unfortunately it seems [bip32utils](https://github.com/prusnak/bip32utils) doesn't have bech32 support yet either.

**Comment by instagibbs** [comment]
@Sjors we could switch to libwally which supports this and has python bindings

**Comment by Sjors** [comment]
It's also used by c-lightning, also one of those Blockstream conspiracies, but at least that means it's maintained :-)

**Comment by instagibbs** [comment]
Yes it is actively maintained and used in multiple products(including GreenAddress), which is nice.

**Comment by Sjors** [comment]
Better still would be to add support for output descriptors to `importmulti` (or a new command). That would also allow cleanly separating m/44' keys from m/49' and m/49' keys. That would keep the users BIP39 seed compatible with (at least some) other wallets.

Is `getnewaddress` smart enough to look for the right key type, and throw an error if the keypool for that type is empty? The GUI would also have to be made a bit smarter, e.g. dis- or enabling the bech32 checkbox, or communicate in some other way that the keypool needs replenishing.

**Comment by achow101** [comment]
I wanted to avoid integrating larger libraries like libwally because there's a lot of additional stuff that we don't need included there.

**Comment by Sjors** [comment]
This should be easier on top of https://github.com/bitcoin/bitcoin/pull/14454 and https://github.com/bitcoin/bitcoin/pull/14565

**Comment by achow101** [comment]
#47 Implements this.
